SearchBayesianSkoptObject: Config 0 Exception. Config: {'topK': 1441, 'alpha1': 0.5433615092629066, 'alpha2': 0.35671127285246457, 'alpha3': 0.04948670460132977} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 1 Exception. Config: {'topK': 1170, 'alpha1': 0.8363876580286128, 'alpha2': 0.7378811705419238, 'alpha3': 0.03434609509396681} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 2 Exception. Config: {'topK': 459, 'alpha1': 0.8333164022345275, 'alpha2': 0.9928358423064018, 'alpha3': 0.8360825847659055} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 3 Exception. Config: {'topK': 1767, 'alpha1': 0.1670337903191406, 'alpha2': 0.49802029452969554, 'alpha3': 0.5954173648741794} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 4 Exception. Config: {'topK': 1837, 'alpha1': 0.6870831871768045, 'alpha2': 0.9826996016496842, 'alpha3': 0.6131925635110846} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 5 Exception. Config: {'topK': 981, 'alpha1': 0.8597435412598594, 'alpha2': 0.5811076534680165, 'alpha3': 0.23895767758892733} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 6 Exception. Config: {'topK': 1693, 'alpha1': 0.5512260432290073, 'alpha2': 0.03073696143727212, 'alpha3': 0.06326740896732887} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 7 Exception. Config: {'topK': 1088, 'alpha1': 0.16381626708849342, 'alpha2': 0.8697101353409278, 'alpha3': 0.033294253794551205} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 8 Exception. Config: {'topK': 933, 'alpha1': 0.03614262057248086, 'alpha2': 0.9288962387430848, 'alpha3': 0.2130831852650384} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 9 Exception. Config: {'topK': 1639, 'alpha1': 0.22965743907879882, 'alpha2': 0.16335337758295856, 'alpha3': 0.4077265158305473} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 10 Exception. Config: {'topK': 856, 'alpha1': 0.7524608648714457, 'alpha2': 0.9697416368024849, 'alpha3': 0.9525948190782667} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 11 Exception. Config: {'topK': 91, 'alpha1': 0.37892484044407393, 'alpha2': 0.07638352133679839, 'alpha3': 0.0024987140337329188} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 12 Exception. Config: {'topK': 1968, 'alpha1': 0.9656291238879913, 'alpha2': 0.8629538330187171, 'alpha3': 0.31904594628379496} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 13 Exception. Config: {'topK': 1392, 'alpha1': 0.5397786775143693, 'alpha2': 0.017554113199359626, 'alpha3': 0.2935439077543763} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 14 Exception. Config: {'topK': 985, 'alpha1': 0.032874835168509205, 'alpha2': 0.2479413486482372, 'alpha3': 0.6886771651002177} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 15 Exception. Config: {'topK': 1973, 'alpha1': 0.6909255274007832, 'alpha2': 0.7150767599483407, 'alpha3': 0.4217422951658253} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 16 Exception. Config: {'topK': 164, 'alpha1': 0.4575753237313809, 'alpha2': 0.4689434507602953, 'alpha3': 0.14363691088747102} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 17 Exception. Config: {'topK': 59, 'alpha1': 0.16589307265548917, 'alpha2': 0.038640257358891435, 'alpha3': 0.6059420724566861} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 18 Exception. Config: {'topK': 1623, 'alpha1': 0.4421184321791539, 'alpha2': 0.005396474089444992, 'alpha3': 0.5120618086524832} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 19 Exception. Config: {'topK': 1690, 'alpha1': 0.15077481492913694, 'alpha2': 0.40113615752503007, 'alpha3': 0.29840160446123704} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 20 Exception. Config: {'topK': 112, 'alpha1': 0.9905780283034228, 'alpha2': 0.11386234563642009, 'alpha3': 0.9363264577732274} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 21 Exception. Config: {'topK': 56, 'alpha1': 0.0001821979949990782, 'alpha2': 0.9509849922209372, 'alpha3': 0.9929075021424456} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 22 Exception. Config: {'topK': 18, 'alpha1': 0.9829394040762875, 'alpha2': 0.09911276845749972, 'alpha3': 0.9974802569998488} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 23 Exception. Config: {'topK': 1786, 'alpha1': 0.025735993279950138, 'alpha2': 0.04536270768725104, 'alpha3': 0.9819821363436203} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 24 Exception. Config: {'topK': 21, 'alpha1': 0.9655961093488618, 'alpha2': 0.05643716489346785, 'alpha3': 0.01569431760993523} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 25 Exception. Config: {'topK': 34, 'alpha1': 0.9429254962462585, 'alpha2': 0.9599288088824696, 'alpha3': 0.992503363036605} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 26 Exception. Config: {'topK': 1926, 'alpha1': 0.9363288041545393, 'alpha2': 0.014173295813417572, 'alpha3': 0.9494505658464523} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 27 Exception. Config: {'topK': 38, 'alpha1': 0.01878151060131663, 'alpha2': 0.9014361550530392, 'alpha3': 0.9463818466982554} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 28 Exception. Config: {'topK': 263, 'alpha1': 0.05861723369179906, 'alpha2': 0.9918690432273263, 'alpha3': 0.004342225507362565} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 29 Exception. Config: {'topK': 1953, 'alpha1': 0.9862117088510776, 'alpha2': 0.9822333263885953, 'alpha3': 0.03502507612637474} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 30 Exception. Config: {'topK': 1901, 'alpha1': 0.06818332337148102, 'alpha2': 0.9672017700993406, 'alpha3': 0.9866229974079403} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 31 Exception. Config: {'topK': 25, 'alpha1': 0.9251965861948414, 'alpha2': 0.0067698674037193225, 'alpha3': 0.9075870235762421} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 32 Exception. Config: {'topK': 109, 'alpha1': 0.03210586379108691, 'alpha2': 0.01932801299398328, 'alpha3': 0.013408449706957497} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 33 Exception. Config: {'topK': 63, 'alpha1': 0.9523053668994151, 'alpha2': 0.9999278017609893, 'alpha3': 0.042785969890130775} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 34 Exception. Config: {'topK': 1848, 'alpha1': 0.033437543150151024, 'alpha2': 0.018442342899427592, 'alpha3': 0.9970895662797629} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 35 Exception. Config: {'topK': 1998, 'alpha1': 0.9953840395767652, 'alpha2': 0.9037933434169885, 'alpha3': 0.9748743111712571} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 36 Exception. Config: {'topK': 9, 'alpha1': 0.9942840349887929, 'alpha2': 0.008634762779986095, 'alpha3': 0.9898526536007249} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 37 Exception. Config: {'topK': 1849, 'alpha1': 0.0013440859729502088, 'alpha2': 0.014789055606910633, 'alpha3': 0.003235548892018795} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 38 Exception. Config: {'topK': 1958, 'alpha1': 0.9594225198050443, 'alpha2': 0.054208652163255114, 'alpha3': 0.005863615718434858} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 39 Exception. Config: {'topK': 64, 'alpha1': 0.028177969367759077, 'alpha2': 0.9127848586847006, 'alpha3': 0.03238112913505176} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 40 Exception. Config: {'topK': 1901, 'alpha1': 0.05577697740146993, 'alpha2': 0.9874336390040908, 'alpha3': 0.9877336237224178} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 41 Exception. Config: {'topK': 1982, 'alpha1': 0.9782280174741582, 'alpha2': 0.9946245348692121, 'alpha3': 0.069360496341089} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 42 Exception. Config: {'topK': 1981, 'alpha1': 0.03148323679955912, 'alpha2': 0.9757618601187927, 'alpha3': 0.9719416355707005} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 43 Exception. Config: {'topK': 18, 'alpha1': 0.9780789190026629, 'alpha2': 0.9500206632170359, 'alpha3': 0.006734832384013066} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 44 Exception. Config: {'topK': 47, 'alpha1': 0.9864405766401187, 'alpha2': 0.9988654546432493, 'alpha3': 0.9544759508652373} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 45 Exception. Config: {'topK': 43, 'alpha1': 0.013834874993286842, 'alpha2': 0.07173186256405852, 'alpha3': 0.9501361044444551} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 46 Exception. Config: {'topK': 59, 'alpha1': 0.06254384080130705, 'alpha2': 0.9828098047812436, 'alpha3': 0.052787036923144584} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 47 Exception. Config: {'topK': 1956, 'alpha1': 0.0015967581161207855, 'alpha2': 0.042875823922209726, 'alpha3': 0.039182522712135966} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 48 Exception. Config: {'topK': 1937, 'alpha1': 0.9462029576194765, 'alpha2': 0.0158357132278828, 'alpha3': 0.9721868857095} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 49 Exception. Config: {'topK': 18, 'alpha1': 0.05561189153026093, 'alpha2': 0.0030239726802286935, 'alpha3': 0.002970882132359521} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 50 Exception. Config: {'topK': 232, 'alpha1': 0.025303790135879918, 'alpha2': 0.9872458825743157, 'alpha3': 0.9786491005801786} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 51 Exception. Config: {'topK': 1937, 'alpha1': 0.9736741851807701, 'alpha2': 0.029098179729429945, 'alpha3': 0.03049452800261427} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 52 Exception. Config: {'topK': 1935, 'alpha1': 0.9461057115312889, 'alpha2': 0.9930741361687491, 'alpha3': 0.0070232839281260135} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 53 Exception. Config: {'topK': 1998, 'alpha1': 0.03271371119006496, 'alpha2': 0.07591753151235103, 'alpha3': 0.9886896816192633} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 54 Exception. Config: {'topK': 41, 'alpha1': 0.0006922334298962315, 'alpha2': 0.9705529489018283, 'alpha3': 0.9681668119550947} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 55 Exception. Config: {'topK': 113, 'alpha1': 0.9942321959497336, 'alpha2': 0.09381441754813627, 'alpha3': 0.9571190525773672} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 56 Exception. Config: {'topK': 2, 'alpha1': 0.8948271341143541, 'alpha2': 0.015209175253016464, 'alpha3': 0.02345820520015985} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 57 Exception. Config: {'topK': 1928, 'alpha1': 0.036871641666307194, 'alpha2': 0.9968516658855817, 'alpha3': 0.002161027665958604} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 58 Exception. Config: {'topK': 63, 'alpha1': 0.9883349725246283, 'alpha2': 0.00013390485845365954, 'alpha3': 0.001989676442009092} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Config 59 Exception. Config: {'topK': 68, 'alpha1': 0.9891122812108869, 'alpha2': 0.025222711278337535, 'alpha3': 0.9836744396885517} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/model/HybridRecommender/HybridMixedSimilarityRecommender.py", line 77, in fit
    len(alpha_list)))
RuntimeError: Weighting list is not right. 4 expected, 3 found

SearchBayesianSkoptObject: Search complete. Best config is None: None
