SearchBayesianSkopt: Config 0 Exception. Config: {'topK': 530, 'shrink': 888, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.7383374171830805, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 1 Exception. Config: {'topK': 435, 'shrink': 1085, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.26777527084936464, 'feature_weighting': 'BM25', 'interactions_feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 2 Exception. Config: {'topK': 576, 'shrink': 631, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.32660677387507314, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 3 Exception. Config: {'topK': 853, 'shrink': 590, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.856075560956143, 'feature_weighting': 'BM25', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 4 Exception. Config: {'topK': 24, 'shrink': 43, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.39879685828212563, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 5 Exception. Config: {'topK': 211, 'shrink': 511, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.0005391195748494, 'feature_weighting': 'none', 'interactions_feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 6 Exception. Config: {'topK': 895, 'shrink': 476, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9367700862295016, 'feature_weighting': 'BM25', 'interactions_feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 7 Exception. Config: {'topK': 281, 'shrink': 804, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.00980381230199723, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 8 Exception. Config: {'topK': 715, 'shrink': 33, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.7731017466015044, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 9 Exception. Config: {'topK': 671, 'shrink': 1159, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.6369822701829913, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 10 Exception. Config: {'topK': 484, 'shrink': 887, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.3103959721758898, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 11 Exception. Config: {'topK': 344, 'shrink': 1383, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.1443490267380463, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 12 Exception. Config: {'topK': 707, 'shrink': 398, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.333533436248211, 'feature_weighting': 'BM25', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 13 Exception. Config: {'topK': 585, 'shrink': 1154, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9597030687873367, 'feature_weighting': 'BM25', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 14 Exception. Config: {'topK': 334, 'shrink': 1407, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.0788009260626141, 'feature_weighting': 'TF-IDF', 'interactions_feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 15 Exception. Config: {'topK': 912, 'shrink': 1038, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.20378101936414456, 'feature_weighting': 'BM25', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 16 Exception. Config: {'topK': 900, 'shrink': 1481, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.11944292088482114, 'feature_weighting': 'none', 'interactions_feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

SearchBayesianSkopt: Config 17 Exception. Config: {'topK': 264, 'shrink': 321, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.14925327069397534, 'feature_weighting': 'BM25', 'interactions_feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 237, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/ParameterTuning/SearchAbstractClass.py", line 229, in _fit_model
    **current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/KNN/ItemKNNCBFRecommender.py", line 49, in fit
    similarity=similarity, **similarity_args)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/course_lib/Base/Similarity/Compute_Similarity.py", line 95, in __init__
    self.compute_similarity_object = Compute_Similarity_Cython(dataMatrix, **args)
  File "Compute_Similarity_Cython.pyx", line 70, in Compute_Similarity_Cython.Compute_Similarity_Cython.__init__
TypeError: __init__() got an unexpected keyword argument 'interactions_feature_weighting'

